BugTracker/BugTracker/Models/UserManager.cs
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.EntityFramework;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace BugTracker.Models
{
    public class UserManager
    {
        static ApplicationDbContext db = new ApplicationDbContext();

        static UserManager<ApplicationUser> userManager = new UserManager<ApplicationUser>(new UserStore<ApplicationUser>(db));

        static RoleManager<IdentityRole> roleManager = new RoleManager<IdentityRole>(new RoleStore<IdentityRole>(db));

        public static void CreateUser(string username)
        {
            userManager.Create(new ApplicationUser { UserName = username });
            db.SaveChanges();
        }
        public static void createRole(string roleName)
        {
            if (!roleManager.RoleExists(roleName))
            {
                roleManager.Create(new IdentityRole { Name = roleName });
                db.SaveChanges();
            }
        }

        public static void removeRole(string roleName)
        {
            if (roleManager.RoleExists(roleName))
            {
                roleManager.Delete(new IdentityRole { Name = roleName });
            }
        }

        public static bool checkUserRole(string userId, string roleName)
        {
            var result = userManager.IsInRole(userId, roleName);

            return result;
        }

        public static bool AddUserToRole(string userId, string roleName)
        {
            if (checkUserRole(userId, roleName))
            {
                return false;
            }
            else
            {
                userManager.AddToRole(userId, roleName);
                return true;
            }
        }

        public static bool RemoveUserFromRole(string userId, string roleName)
        {
            if (!checkUserRole(userId, roleName))
            {
                return false;
            }
            else
            {
                userManager.RemoveFromRole(userId, roleName);

                return true;
            }
        }
    }
}

BugTracker/BugTracker/Controllers/ProjectsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using BugTracker.Models;

namespace BugTracker.Controllers
{
    public class ProjectsController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: Projects
        [Authorize(Roles = "Admin, Project Manager")]
        public ActionResult Index()
        {
            return View(db.Projects.ToList());
        }

        // GET: Projects/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Project project = db.Projects.Find(id);
            if (project == null)
            {
                return HttpNotFound();
            }
            return View(project);
        }

        // GET: Projects/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Projects/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,Name")] Project project)
        {
            if (ModelState.IsValid)
            {
                db.Projects.Add(project);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(project);
        }
        [Authorize(Roles = "Admin, Project Manager")]
        // GET: Projects/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Project project = db.Projects.Find(id);
            if (project == null)
            {
                return HttpNotFound();
            }
            return View(project);
        }

        // POST: Projects/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [Authorize(Roles = "Admin, Project Manager")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,Name")] Project project)
        {
            if (ModelState.IsValid)
            {
                db.Entry(project).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(project);
        }

        // GET: Projects/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Project project = db.Projects.Find(id);
            if (project == null)
            {
                return HttpNotFound();
            }
            return View(project);
        }

        // POST: Projects/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Project project = db.Projects.Find(id);
            db.Projects.Remove(project);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

BugTracker/BugTracker/Controllers/UserManagersController.cs
using BugTracker.Models;
using BugTracker.Repositories;
using Microsoft.AspNet.Identity.EntityFramework;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;

namespace BugTracker.Controllers
{
    public class UserManagersController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();
        public TicketRepository tr = new TicketRepository();
        public UserManager um = new UserManager();

        // GET: UserManagers
        [Authorize(Roles="Administrator, Project Manager")]
        public ActionResult Index()
        {
            var roles = db.Roles.ToList();
            return View(roles);
        }
        //GET
        [Authorize(Roles = "Administrator, Project Manager")]
        public ActionResult Create()
        {
            var Role = new IdentityRole();
            return View(Role);
        }
        //POST
        [Authorize(Roles = "Administrator, Project Manager")]
        [HttpPost]
        public ActionResult Create([Bind(Include = "Name")] IdentityRole role)
        {
            if(ModelState.IsValid)
            {
                db.Roles.Add(role);
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(role);
            
        }
        //GET
        [Authorize(Roles = "Administrator, Project Manager")]
        [HttpGet]
        public ActionResult AssignDeveloperToTicket()
        {
            ViewBag.TicketName = new SelectList(db.Tickets.ToList(), "Title", "Title");
            var developers = db.Roles.Where(r => r.Name == "Developer").Select(u=>u.Users).FirstOrDefault();
            ViewBag.UserName = new SelectList(developers, "UserId", "UserName");
            return View();
        }
        //POST
        [Authorize(Roles = "Administrator, Project Manager")]
        [HttpPost]
        public ActionResult AssignDeveloperToTicket(ApplicationUser user, Ticket ticket)
        {
            if (ModelState.IsValid)
            {
                user.AssignedToTickets.Add(ticket);

                if (!db.TicketNotifications.Any())
                {
                    TicketNotification notification = new TicketNotification("New Assigned Ticket", ticket.Id, user.Id);

                    db.TicketNotifications.Add(notification);
                }

                db.SaveChanges();
                return RedirectToAction("Index", "UserManager");
            }

            ViewBag.TicketName = new SelectList(db.Projects.ToList(), "Title", "Title");
            var developers = db.Roles.Where(r => r.Name == "Developer").Select(u => u.Users).FirstOrDefault();
            ViewBag.UserName = new SelectList(developers, "UserId", "UserName");
            return View(ticket);
        }
    }
}

BugTracker/BugTracker/Views/UserManagers/AssignDeveloperToProject.cshtml
@model BugTracker.Models.RegisterViewModel
@{
    ViewBag.Title = "AssignDeveloperToProject";
}

<h2>Assign Developer to Project</h2>

@using (Html.BeginForm("AssignDeveloperToProject", "UserManager", FormMethod.Post))
{
    <div>
        @Html.Label("Select Project")
        @Html.DropDownList("ProjectName")
    </div>
    <div>
        @Html.Label("Select User")
        @Html.DropDownList("UserName")
    </div>

    <input type="submit" />
}

BugTracker/BugTracker/Views/UserManagers/AssignDeveloperToTicket.cshtml
@model BugTracker.Models.RegisterViewModel
@{
    ViewBag.Title = "AssignDeveloperToTicket";
}

<h2>Assign Developer to Project</h2>

@using (Html.BeginForm("AssignDeveloperToTicket", "UserManager", FormMethod.Post))
{
    <div>
        @Html.Label("Select Ticket")
        @Html.DropDownList("TicketName")
    </div>
    <div>
        @Html.Label("Select User")
        @Html.DropDownList("UserName")
    </div>

    <input type="submit" />
}

BugTracker/BugTracker/Views/UserManagers/Create.cshtml
@model Microsoft.AspNet.Identity.EntityFramework.IdentityRole

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>


@using (Html.BeginForm())
{
    @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
    <div class="col-md-10">
        @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
        @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
    </div>


}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

BugTracker/BugTracker/Views/UserManagers/Index.cshtml
@model IEnumerable<Microsoft.AspNet.Identity.EntityFramework.IdentityRole>

@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

<div>
    @Html.ActionLink("Create Role", "Create", "Role")
    @Html.ActionLink("Assign Role", "AssignRole", "Account")
    @Html.ActionLink("Create New Project", "Create", "Projects")
    @Html.ActionLink("Assign Project to Developer", "#SOMEFUNCTION", "UserManagers") @*//still need to do*@ 
    @Html.ActionLink("View All Projects", "Index", "Projects")
</div>